name = "ttt-calculator"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "ttt-db"
database_id = "2da84074-4076-4e93-bdb1-40212beddf7e"

[dev]
port = 8787
